### ISSUE TITLE
Stabile version

### ISSUE THREAD

**Issue by Kflash** [ugma/ugma#8]
@mehranhatami I spent some hours now to clean the codebase and remove bugs. Ugma should be stable, but still waiting for the test cases to be sure.

Can you test ugma, and try to use it in production. Example create a popup dialogbox, and let me know of the result?

Any feedback on ugma as it is today are wanted !!

**Comment by mehranhatami** [comment]
@KFlash I've got the tests under process, and it seems I have almost passed
the half of the way. But regarding using Ugma in production, I haven't
still had the chance to do that, because my current project has no room for
any library to be used, it is a NodeJS project on the server for an android
game. So not in production, but I could play around with it to see how it
actually works. I'll let you know once I had any feedback.

**Comment by Kflash** [comment]
@mehranhatami  Ok. I just put together a popup dialogbox and it's works, and the performance great. But try to set up a benchmark system also for testing purposes, so we could find any bottle necks if any.
